/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 6.2.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QGridLayout>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTextBrowser>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QStackedWidget *stackedWidget;
    QWidget *cardNumber;
    QLabel *error;
    QLabel *enterCard;
    QPushButton *p1;
    QPushButton *p2;
    QPushButton *p3;
    QPushButton *pc;
    QTextBrowser *input;
    QPushButton *p4;
    QPushButton *p5;
    QPushButton *pca;
    QPushButton *p0;
    QPushButton *p8;
    QPushButton *p7;
    QPushButton *p6;
    QPushButton *p9;
    QPushButton *psubmit;
    QLabel *errorCardNum;
    QWidget *PIN;
    QLabel *enterPin;
    QPushButton *pushButton_1;
    QPushButton *pushButton_2;
    QPushButton *pushButton_3;
    QTextBrowser *inputPin;
    QPushButton *pushButton_4;
    QPushButton *pushButton_5;
    QPushButton *pushButton_6;
    QPushButton *pushButton_7;
    QPushButton *pushButton_8;
    QPushButton *pushButton_9;
    QPushButton *pushButton_c;
    QPushButton *pushButton;
    QPushButton *pushButton_ca;
    QPushButton *pushButton_back;
    QPushButton *pushButton_submit;
    QLabel *errorPin;
    QPushButton *see;
    QWidget *bankOperations;
    QPushButton *changePin;
    QPushButton *checkBalance_2;
    QPushButton *charityTransfer;
    QPushButton *withdrawMoney2;
    QPushButton *moneyTransfer;
    QPushButton *logOut;
    QPushButton *mobileTransfer;
    QLabel *welcoming;
    QLabel *lastOpSuccess;
    QWidget *withdrawMoney;
    QPushButton *pu_1;
    QPushButton *pu_2;
    QPushButton *pu_3;
    QPushButton *pu_4;
    QPushButton *pu_5;
    QPushButton *pu_6;
    QPushButton *pu_8;
    QPushButton *pu_7;
    QPushButton *pu_cA;
    QPushButton *pu_9;
    QPushButton *pu_0;
    QPushButton *pu_c;
    QLabel *label;
    QTextBrowser *inputAmount;
    QLabel *la_error;
    QPushButton *bck;
    QPushButton *sbm;
    QLabel *transferTo_2;
    QTextBrowser *trT;
    QLabel *charityMessage;
    QWidget *checkBalance;
    QLabel *balanceLabel;
    QPushButton *backBank;
    QWidget *changePinWindow;
    QPushButton *p_1;
    QPushButton *p_2;
    QPushButton *p_3;
    QPushButton *p_4;
    QPushButton *p_5;
    QPushButton *p_7;
    QPushButton *p_6;
    QPushButton *p_c_a;
    QPushButton *p_0;
    QPushButton *p_c;
    QPushButton *p_9;
    QPushButton *p_8;
    QPushButton *p_back;
    QLabel *old;
    QLabel *repeat;
    QLabel *newL;
    QPushButton *p_submit;
    QLabel *p_error;
    QTextBrowser *oldPin;
    QTextBrowser *newPin;
    QTextBrowser *newPinRepeat;
    QWidget *charityEnumeration;
    QLabel *transferTo;
    QPushButton *back;
    QWidget *gridLayoutWidget;
    QGridLayout *gridLayout;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(800, 600);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        stackedWidget = new QStackedWidget(centralwidget);
        stackedWidget->setObjectName(QString::fromUtf8("stackedWidget"));
        stackedWidget->setGeometry(QRect(0, 0, 591, 321));
        cardNumber = new QWidget();
        cardNumber->setObjectName(QString::fromUtf8("cardNumber"));
        error = new QLabel(cardNumber);
        error->setObjectName(QString::fromUtf8("error"));
        error->setGeometry(QRect(80, 260, 131, 31));
        enterCard = new QLabel(cardNumber);
        enterCard->setObjectName(QString::fromUtf8("enterCard"));
        enterCard->setGeometry(QRect(110, 0, 361, 61));
        enterCard->setStyleSheet(QString::fromUtf8("font: 75 24pt \"MS Shell Dlg 2\";"));
        p1 = new QPushButton(cardNumber);
        p1->setObjectName(QString::fromUtf8("p1"));
        p1->setGeometry(QRect(320, 90, 51, 51));
        p1->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        p2 = new QPushButton(cardNumber);
        p2->setObjectName(QString::fromUtf8("p2"));
        p2->setGeometry(QRect(380, 90, 51, 51));
        p2->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        p3 = new QPushButton(cardNumber);
        p3->setObjectName(QString::fromUtf8("p3"));
        p3->setGeometry(QRect(440, 90, 51, 51));
        p3->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        pc = new QPushButton(cardNumber);
        pc->setObjectName(QString::fromUtf8("pc"));
        pc->setGeometry(QRect(440, 240, 51, 51));
        pc->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        input = new QTextBrowser(cardNumber);
        input->setObjectName(QString::fromUtf8("input"));
        input->setGeometry(QRect(80, 130, 141, 51));
        p4 = new QPushButton(cardNumber);
        p4->setObjectName(QString::fromUtf8("p4"));
        p4->setGeometry(QRect(320, 140, 51, 51));
        p4->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        p5 = new QPushButton(cardNumber);
        p5->setObjectName(QString::fromUtf8("p5"));
        p5->setGeometry(QRect(380, 140, 51, 51));
        p5->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        pca = new QPushButton(cardNumber);
        pca->setObjectName(QString::fromUtf8("pca"));
        pca->setGeometry(QRect(320, 240, 51, 51));
        pca->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        p0 = new QPushButton(cardNumber);
        p0->setObjectName(QString::fromUtf8("p0"));
        p0->setGeometry(QRect(380, 240, 51, 51));
        p0->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        p8 = new QPushButton(cardNumber);
        p8->setObjectName(QString::fromUtf8("p8"));
        p8->setGeometry(QRect(380, 190, 51, 51));
        p8->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        p7 = new QPushButton(cardNumber);
        p7->setObjectName(QString::fromUtf8("p7"));
        p7->setGeometry(QRect(320, 190, 51, 51));
        p7->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        p6 = new QPushButton(cardNumber);
        p6->setObjectName(QString::fromUtf8("p6"));
        p6->setGeometry(QRect(440, 140, 51, 51));
        p6->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        p9 = new QPushButton(cardNumber);
        p9->setObjectName(QString::fromUtf8("p9"));
        p9->setGeometry(QRect(440, 190, 51, 51));
        p9->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        psubmit = new QPushButton(cardNumber);
        psubmit->setObjectName(QString::fromUtf8("psubmit"));
        psubmit->setGeometry(QRect(520, 290, 71, 31));
        psubmit->setStyleSheet(QString::fromUtf8(""));
        errorCardNum = new QLabel(cardNumber);
        errorCardNum->setObjectName(QString::fromUtf8("errorCardNum"));
        errorCardNum->setGeometry(QRect(80, 230, 171, 31));
        stackedWidget->addWidget(cardNumber);
        PIN = new QWidget();
        PIN->setObjectName(QString::fromUtf8("PIN"));
        enterPin = new QLabel(PIN);
        enterPin->setObjectName(QString::fromUtf8("enterPin"));
        enterPin->setGeometry(QRect(150, 0, 241, 71));
        enterPin->setStyleSheet(QString::fromUtf8("font: 75 24pt \"MS Shell Dlg 2\";"));
        pushButton_1 = new QPushButton(PIN);
        pushButton_1->setObjectName(QString::fromUtf8("pushButton_1"));
        pushButton_1->setGeometry(QRect(300, 80, 51, 51));
        pushButton_1->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        pushButton_2 = new QPushButton(PIN);
        pushButton_2->setObjectName(QString::fromUtf8("pushButton_2"));
        pushButton_2->setGeometry(QRect(360, 80, 51, 51));
        pushButton_2->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        pushButton_3 = new QPushButton(PIN);
        pushButton_3->setObjectName(QString::fromUtf8("pushButton_3"));
        pushButton_3->setGeometry(QRect(420, 80, 51, 51));
        pushButton_3->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        inputPin = new QTextBrowser(PIN);
        inputPin->setObjectName(QString::fromUtf8("inputPin"));
        inputPin->setGeometry(QRect(20, 120, 191, 51));
        pushButton_4 = new QPushButton(PIN);
        pushButton_4->setObjectName(QString::fromUtf8("pushButton_4"));
        pushButton_4->setGeometry(QRect(300, 130, 51, 51));
        pushButton_4->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        pushButton_5 = new QPushButton(PIN);
        pushButton_5->setObjectName(QString::fromUtf8("pushButton_5"));
        pushButton_5->setGeometry(QRect(360, 130, 51, 51));
        pushButton_5->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        pushButton_6 = new QPushButton(PIN);
        pushButton_6->setObjectName(QString::fromUtf8("pushButton_6"));
        pushButton_6->setGeometry(QRect(420, 130, 51, 51));
        pushButton_6->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        pushButton_7 = new QPushButton(PIN);
        pushButton_7->setObjectName(QString::fromUtf8("pushButton_7"));
        pushButton_7->setGeometry(QRect(300, 180, 51, 51));
        pushButton_7->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        pushButton_8 = new QPushButton(PIN);
        pushButton_8->setObjectName(QString::fromUtf8("pushButton_8"));
        pushButton_8->setGeometry(QRect(360, 180, 51, 51));
        pushButton_8->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        pushButton_9 = new QPushButton(PIN);
        pushButton_9->setObjectName(QString::fromUtf8("pushButton_9"));
        pushButton_9->setGeometry(QRect(420, 180, 51, 51));
        pushButton_9->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        pushButton_c = new QPushButton(PIN);
        pushButton_c->setObjectName(QString::fromUtf8("pushButton_c"));
        pushButton_c->setGeometry(QRect(300, 230, 51, 51));
        pushButton_c->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        pushButton = new QPushButton(PIN);
        pushButton->setObjectName(QString::fromUtf8("pushButton"));
        pushButton->setGeometry(QRect(360, 230, 51, 51));
        pushButton->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        pushButton_ca = new QPushButton(PIN);
        pushButton_ca->setObjectName(QString::fromUtf8("pushButton_ca"));
        pushButton_ca->setGeometry(QRect(420, 230, 51, 51));
        pushButton_ca->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        pushButton_back = new QPushButton(PIN);
        pushButton_back->setObjectName(QString::fromUtf8("pushButton_back"));
        pushButton_back->setGeometry(QRect(510, 250, 81, 31));
        pushButton_back->setStyleSheet(QString::fromUtf8(""));
        pushButton_submit = new QPushButton(PIN);
        pushButton_submit->setObjectName(QString::fromUtf8("pushButton_submit"));
        pushButton_submit->setGeometry(QRect(510, 290, 81, 31));
        pushButton_submit->setStyleSheet(QString::fromUtf8(""));
        errorPin = new QLabel(PIN);
        errorPin->setObjectName(QString::fromUtf8("errorPin"));
        errorPin->setGeometry(QRect(30, 210, 221, 51));
        see = new QPushButton(PIN);
        see->setObjectName(QString::fromUtf8("see"));
        see->setGeometry(QRect(160, 120, 51, 51));
        stackedWidget->addWidget(PIN);
        bankOperations = new QWidget();
        bankOperations->setObjectName(QString::fromUtf8("bankOperations"));
        changePin = new QPushButton(bankOperations);
        changePin->setObjectName(QString::fromUtf8("changePin"));
        changePin->setGeometry(QRect(110, 70, 101, 91));
        checkBalance_2 = new QPushButton(bankOperations);
        checkBalance_2->setObjectName(QString::fromUtf8("checkBalance_2"));
        checkBalance_2->setGeometry(QRect(220, 70, 101, 91));
        charityTransfer = new QPushButton(bankOperations);
        charityTransfer->setObjectName(QString::fromUtf8("charityTransfer"));
        charityTransfer->setGeometry(QRect(110, 170, 101, 91));
        withdrawMoney2 = new QPushButton(bankOperations);
        withdrawMoney2->setObjectName(QString::fromUtf8("withdrawMoney2"));
        withdrawMoney2->setGeometry(QRect(330, 70, 101, 91));
        moneyTransfer = new QPushButton(bankOperations);
        moneyTransfer->setObjectName(QString::fromUtf8("moneyTransfer"));
        moneyTransfer->setGeometry(QRect(330, 170, 101, 91));
        logOut = new QPushButton(bankOperations);
        logOut->setObjectName(QString::fromUtf8("logOut"));
        logOut->setGeometry(QRect(500, 20, 75, 23));
        mobileTransfer = new QPushButton(bankOperations);
        mobileTransfer->setObjectName(QString::fromUtf8("mobileTransfer"));
        mobileTransfer->setGeometry(QRect(220, 170, 101, 91));
        welcoming = new QLabel(bankOperations);
        welcoming->setObjectName(QString::fromUtf8("welcoming"));
        welcoming->setGeometry(QRect(120, 20, 311, 31));
        lastOpSuccess = new QLabel(bankOperations);
        lastOpSuccess->setObjectName(QString::fromUtf8("lastOpSuccess"));
        lastOpSuccess->setGeometry(QRect(200, 280, 151, 16));
        stackedWidget->addWidget(bankOperations);
        withdrawMoney = new QWidget();
        withdrawMoney->setObjectName(QString::fromUtf8("withdrawMoney"));
        pu_1 = new QPushButton(withdrawMoney);
        pu_1->setObjectName(QString::fromUtf8("pu_1"));
        pu_1->setGeometry(QRect(260, 70, 51, 51));
        pu_1->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        pu_2 = new QPushButton(withdrawMoney);
        pu_2->setObjectName(QString::fromUtf8("pu_2"));
        pu_2->setGeometry(QRect(320, 70, 51, 51));
        pu_2->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        pu_3 = new QPushButton(withdrawMoney);
        pu_3->setObjectName(QString::fromUtf8("pu_3"));
        pu_3->setGeometry(QRect(380, 70, 51, 51));
        pu_3->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        pu_4 = new QPushButton(withdrawMoney);
        pu_4->setObjectName(QString::fromUtf8("pu_4"));
        pu_4->setGeometry(QRect(260, 130, 51, 51));
        pu_4->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        pu_5 = new QPushButton(withdrawMoney);
        pu_5->setObjectName(QString::fromUtf8("pu_5"));
        pu_5->setGeometry(QRect(320, 130, 51, 51));
        pu_5->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        pu_6 = new QPushButton(withdrawMoney);
        pu_6->setObjectName(QString::fromUtf8("pu_6"));
        pu_6->setGeometry(QRect(380, 130, 51, 51));
        pu_6->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        pu_8 = new QPushButton(withdrawMoney);
        pu_8->setObjectName(QString::fromUtf8("pu_8"));
        pu_8->setGeometry(QRect(320, 190, 51, 51));
        pu_8->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        pu_7 = new QPushButton(withdrawMoney);
        pu_7->setObjectName(QString::fromUtf8("pu_7"));
        pu_7->setGeometry(QRect(260, 190, 51, 51));
        pu_7->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        pu_cA = new QPushButton(withdrawMoney);
        pu_cA->setObjectName(QString::fromUtf8("pu_cA"));
        pu_cA->setGeometry(QRect(380, 250, 51, 51));
        pu_cA->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        pu_9 = new QPushButton(withdrawMoney);
        pu_9->setObjectName(QString::fromUtf8("pu_9"));
        pu_9->setGeometry(QRect(380, 190, 51, 51));
        pu_9->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        pu_0 = new QPushButton(withdrawMoney);
        pu_0->setObjectName(QString::fromUtf8("pu_0"));
        pu_0->setGeometry(QRect(320, 250, 51, 51));
        pu_0->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        pu_c = new QPushButton(withdrawMoney);
        pu_c->setObjectName(QString::fromUtf8("pu_c"));
        pu_c->setGeometry(QRect(260, 250, 51, 51));
        pu_c->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        label = new QLabel(withdrawMoney);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(10, 150, 241, 71));
        label->setStyleSheet(QString::fromUtf8("font: 12pt \"MS Shell Dlg 2\";"));
        inputAmount = new QTextBrowser(withdrawMoney);
        inputAmount->setObjectName(QString::fromUtf8("inputAmount"));
        inputAmount->setGeometry(QRect(20, 210, 191, 51));
        la_error = new QLabel(withdrawMoney);
        la_error->setObjectName(QString::fromUtf8("la_error"));
        la_error->setGeometry(QRect(20, 280, 171, 31));
        bck = new QPushButton(withdrawMoney);
        bck->setObjectName(QString::fromUtf8("bck"));
        bck->setGeometry(QRect(510, 290, 75, 23));
        sbm = new QPushButton(withdrawMoney);
        sbm->setObjectName(QString::fromUtf8("sbm"));
        sbm->setGeometry(QRect(510, 260, 75, 23));
        transferTo_2 = new QLabel(withdrawMoney);
        transferTo_2->setObjectName(QString::fromUtf8("transferTo_2"));
        transferTo_2->setGeometry(QRect(10, 60, 201, 31));
        transferTo_2->setStyleSheet(QString::fromUtf8("font: 12pt \"MS Shell Dlg 2\";"));
        trT = new QTextBrowser(withdrawMoney);
        trT->setObjectName(QString::fromUtf8("trT"));
        trT->setGeometry(QRect(20, 100, 191, 51));
        charityMessage = new QLabel(withdrawMoney);
        charityMessage->setObjectName(QString::fromUtf8("charityMessage"));
        charityMessage->setGeometry(QRect(150, 0, 331, 41));
        stackedWidget->addWidget(withdrawMoney);
        checkBalance = new QWidget();
        checkBalance->setObjectName(QString::fromUtf8("checkBalance"));
        balanceLabel = new QLabel(checkBalance);
        balanceLabel->setObjectName(QString::fromUtf8("balanceLabel"));
        balanceLabel->setGeometry(QRect(10, 100, 681, 91));
        backBank = new QPushButton(checkBalance);
        backBank->setObjectName(QString::fromUtf8("backBank"));
        backBank->setGeometry(QRect(510, 290, 75, 23));
        stackedWidget->addWidget(checkBalance);
        changePinWindow = new QWidget();
        changePinWindow->setObjectName(QString::fromUtf8("changePinWindow"));
        p_1 = new QPushButton(changePinWindow);
        p_1->setObjectName(QString::fromUtf8("p_1"));
        p_1->setGeometry(QRect(260, 50, 51, 51));
        p_1->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        p_2 = new QPushButton(changePinWindow);
        p_2->setObjectName(QString::fromUtf8("p_2"));
        p_2->setGeometry(QRect(320, 50, 51, 51));
        p_2->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        p_3 = new QPushButton(changePinWindow);
        p_3->setObjectName(QString::fromUtf8("p_3"));
        p_3->setGeometry(QRect(380, 50, 51, 51));
        p_3->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        p_4 = new QPushButton(changePinWindow);
        p_4->setObjectName(QString::fromUtf8("p_4"));
        p_4->setGeometry(QRect(260, 110, 51, 51));
        p_4->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        p_5 = new QPushButton(changePinWindow);
        p_5->setObjectName(QString::fromUtf8("p_5"));
        p_5->setGeometry(QRect(320, 110, 51, 51));
        p_5->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        p_7 = new QPushButton(changePinWindow);
        p_7->setObjectName(QString::fromUtf8("p_7"));
        p_7->setGeometry(QRect(260, 170, 51, 51));
        p_7->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        p_6 = new QPushButton(changePinWindow);
        p_6->setObjectName(QString::fromUtf8("p_6"));
        p_6->setGeometry(QRect(380, 110, 51, 51));
        p_6->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        p_c_a = new QPushButton(changePinWindow);
        p_c_a->setObjectName(QString::fromUtf8("p_c_a"));
        p_c_a->setGeometry(QRect(380, 230, 51, 51));
        p_c_a->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        p_0 = new QPushButton(changePinWindow);
        p_0->setObjectName(QString::fromUtf8("p_0"));
        p_0->setGeometry(QRect(320, 230, 51, 51));
        p_0->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        p_c = new QPushButton(changePinWindow);
        p_c->setObjectName(QString::fromUtf8("p_c"));
        p_c->setGeometry(QRect(260, 230, 51, 51));
        p_c->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        p_9 = new QPushButton(changePinWindow);
        p_9->setObjectName(QString::fromUtf8("p_9"));
        p_9->setGeometry(QRect(380, 170, 51, 51));
        p_9->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        p_8 = new QPushButton(changePinWindow);
        p_8->setObjectName(QString::fromUtf8("p_8"));
        p_8->setGeometry(QRect(320, 170, 51, 51));
        p_8->setStyleSheet(QString::fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"));
        p_back = new QPushButton(changePinWindow);
        p_back->setObjectName(QString::fromUtf8("p_back"));
        p_back->setGeometry(QRect(510, 280, 81, 31));
        old = new QLabel(changePinWindow);
        old->setObjectName(QString::fromUtf8("old"));
        old->setGeometry(QRect(20, 30, 101, 41));
        old->setStyleSheet(QString::fromUtf8("font: 11pt \"MS Shell Dlg 2\";"));
        repeat = new QLabel(changePinWindow);
        repeat->setObjectName(QString::fromUtf8("repeat"));
        repeat->setGeometry(QRect(20, 200, 171, 41));
        repeat->setStyleSheet(QString::fromUtf8("font: 11pt \"MS Shell Dlg 2\";"));
        newL = new QLabel(changePinWindow);
        newL->setObjectName(QString::fromUtf8("newL"));
        newL->setGeometry(QRect(20, 110, 101, 41));
        newL->setStyleSheet(QString::fromUtf8("font: 11pt \"MS Shell Dlg 2\";"));
        p_submit = new QPushButton(changePinWindow);
        p_submit->setObjectName(QString::fromUtf8("p_submit"));
        p_submit->setGeometry(QRect(510, 240, 81, 31));
        p_error = new QLabel(changePinWindow);
        p_error->setObjectName(QString::fromUtf8("p_error"));
        p_error->setGeometry(QRect(20, 295, 191, 16));
        oldPin = new QTextBrowser(changePinWindow);
        oldPin->setObjectName(QString::fromUtf8("oldPin"));
        oldPin->setGeometry(QRect(20, 70, 171, 51));
        newPin = new QTextBrowser(changePinWindow);
        newPin->setObjectName(QString::fromUtf8("newPin"));
        newPin->setGeometry(QRect(20, 150, 171, 51));
        newPinRepeat = new QTextBrowser(changePinWindow);
        newPinRepeat->setObjectName(QString::fromUtf8("newPinRepeat"));
        newPinRepeat->setGeometry(QRect(20, 240, 171, 51));
        stackedWidget->addWidget(changePinWindow);
        charityEnumeration = new QWidget();
        charityEnumeration->setObjectName(QString::fromUtf8("charityEnumeration"));
        transferTo = new QLabel(charityEnumeration);
        transferTo->setObjectName(QString::fromUtf8("transferTo"));
        transferTo->setGeometry(QRect(20, 50, 161, 31));
        transferTo->setStyleSheet(QString::fromUtf8("font: 11pt \"MS Shell Dlg 2\";"));
        back = new QPushButton(charityEnumeration);
        back->setObjectName(QString::fromUtf8("back"));
        back->setGeometry(QRect(500, 280, 81, 31));
        gridLayoutWidget = new QWidget(charityEnumeration);
        gridLayoutWidget->setObjectName(QString::fromUtf8("gridLayoutWidget"));
        gridLayoutWidget->setGeometry(QRect(0, 0, 581, 271));
        gridLayout = new QGridLayout(gridLayoutWidget);
        gridLayout->setObjectName(QString::fromUtf8("gridLayout"));
        gridLayout->setContentsMargins(0, 0, 0, 0);
        stackedWidget->addWidget(charityEnumeration);
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 800, 21));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);

        retranslateUi(MainWindow);

        stackedWidget->setCurrentIndex(5);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "MainWindow", nullptr));
        error->setText(QString());
        enterCard->setText(QCoreApplication::translate("MainWindow", "Enter your card number:", nullptr));
        p1->setText(QCoreApplication::translate("MainWindow", "1", nullptr));
        p2->setText(QCoreApplication::translate("MainWindow", "2", nullptr));
        p3->setText(QCoreApplication::translate("MainWindow", "3", nullptr));
        pc->setText(QCoreApplication::translate("MainWindow", "<-", nullptr));
        p4->setText(QCoreApplication::translate("MainWindow", "4", nullptr));
        p5->setText(QCoreApplication::translate("MainWindow", "5", nullptr));
        pca->setText(QCoreApplication::translate("MainWindow", "<-A", nullptr));
        p0->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        p8->setText(QCoreApplication::translate("MainWindow", "8", nullptr));
        p7->setText(QCoreApplication::translate("MainWindow", "7", nullptr));
        p6->setText(QCoreApplication::translate("MainWindow", "6", nullptr));
        p9->setText(QCoreApplication::translate("MainWindow", "9", nullptr));
        psubmit->setText(QCoreApplication::translate("MainWindow", "Submit", nullptr));
        errorCardNum->setText(QString());
        enterPin->setText(QCoreApplication::translate("MainWindow", "Enter your PIN:", nullptr));
        pushButton_1->setText(QCoreApplication::translate("MainWindow", "1", nullptr));
        pushButton_2->setText(QCoreApplication::translate("MainWindow", "2", nullptr));
        pushButton_3->setText(QCoreApplication::translate("MainWindow", "3", nullptr));
        pushButton_4->setText(QCoreApplication::translate("MainWindow", "4", nullptr));
        pushButton_5->setText(QCoreApplication::translate("MainWindow", "5", nullptr));
        pushButton_6->setText(QCoreApplication::translate("MainWindow", "6", nullptr));
        pushButton_7->setText(QCoreApplication::translate("MainWindow", "7", nullptr));
        pushButton_8->setText(QCoreApplication::translate("MainWindow", "8", nullptr));
        pushButton_9->setText(QCoreApplication::translate("MainWindow", "9", nullptr));
        pushButton_c->setText(QCoreApplication::translate("MainWindow", "<-", nullptr));
        pushButton->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        pushButton_ca->setText(QCoreApplication::translate("MainWindow", "<-A", nullptr));
        pushButton_back->setText(QCoreApplication::translate("MainWindow", "Back", nullptr));
        pushButton_submit->setText(QCoreApplication::translate("MainWindow", "Submit", nullptr));
        errorPin->setText(QString());
        see->setText(QCoreApplication::translate("MainWindow", "See", nullptr));
        changePin->setText(QCoreApplication::translate("MainWindow", "Change PIN", nullptr));
        checkBalance_2->setText(QCoreApplication::translate("MainWindow", "Check balance", nullptr));
        charityTransfer->setText(QCoreApplication::translate("MainWindow", "Charity transfer", nullptr));
        withdrawMoney2->setText(QCoreApplication::translate("MainWindow", "Withdraw money", nullptr));
        moneyTransfer->setText(QCoreApplication::translate("MainWindow", "Transfer money", nullptr));
        logOut->setText(QCoreApplication::translate("MainWindow", "Log out", nullptr));
        mobileTransfer->setText(QCoreApplication::translate("MainWindow", "Transfer to mobile", nullptr));
        welcoming->setText(QString());
        lastOpSuccess->setText(QString());
        pu_1->setText(QCoreApplication::translate("MainWindow", "1", nullptr));
        pu_2->setText(QCoreApplication::translate("MainWindow", "2", nullptr));
        pu_3->setText(QCoreApplication::translate("MainWindow", "3", nullptr));
        pu_4->setText(QCoreApplication::translate("MainWindow", "4", nullptr));
        pu_5->setText(QCoreApplication::translate("MainWindow", "5", nullptr));
        pu_6->setText(QCoreApplication::translate("MainWindow", "6", nullptr));
        pu_8->setText(QCoreApplication::translate("MainWindow", "8", nullptr));
        pu_7->setText(QCoreApplication::translate("MainWindow", "7", nullptr));
        pu_cA->setText(QCoreApplication::translate("MainWindow", "<-A", nullptr));
        pu_9->setText(QCoreApplication::translate("MainWindow", "9", nullptr));
        pu_0->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        pu_c->setText(QCoreApplication::translate("MainWindow", "<-", nullptr));
        label->setText(QCoreApplication::translate("MainWindow", "The amount of money to transfer \n"
" (UAH) :", nullptr));
        la_error->setText(QString());
        bck->setText(QCoreApplication::translate("MainWindow", "Back", nullptr));
        sbm->setText(QCoreApplication::translate("MainWindow", "Submit", nullptr));
        transferTo_2->setText(QString());
        charityMessage->setText(QString());
        balanceLabel->setText(QCoreApplication::translate("MainWindow", "Your balance is: ", nullptr));
        backBank->setText(QCoreApplication::translate("MainWindow", "Back", nullptr));
        p_1->setText(QCoreApplication::translate("MainWindow", "1", nullptr));
        p_2->setText(QCoreApplication::translate("MainWindow", "2", nullptr));
        p_3->setText(QCoreApplication::translate("MainWindow", "3", nullptr));
        p_4->setText(QCoreApplication::translate("MainWindow", "4", nullptr));
        p_5->setText(QCoreApplication::translate("MainWindow", "5", nullptr));
        p_7->setText(QCoreApplication::translate("MainWindow", "7", nullptr));
        p_6->setText(QCoreApplication::translate("MainWindow", "6", nullptr));
        p_c_a->setText(QCoreApplication::translate("MainWindow", "<-A", nullptr));
        p_0->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        p_c->setText(QCoreApplication::translate("MainWindow", "<-", nullptr));
        p_9->setText(QCoreApplication::translate("MainWindow", "9", nullptr));
        p_8->setText(QCoreApplication::translate("MainWindow", "8", nullptr));
        p_back->setText(QCoreApplication::translate("MainWindow", "Back", nullptr));
        old->setText(QCoreApplication::translate("MainWindow", "Old pincode:", nullptr));
        repeat->setText(QCoreApplication::translate("MainWindow", "Repeat new pincode:", nullptr));
        newL->setText(QCoreApplication::translate("MainWindow", "New pincode:", nullptr));
        p_submit->setText(QCoreApplication::translate("MainWindow", "Submit", nullptr));
        p_error->setText(QString());
        transferTo->setText(QString());
        back->setText(QCoreApplication::translate("MainWindow", "Back", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
